apiVersion: v1
kind: Service
metadata:
  name: goods-web-service
  namespace: lnmp
spec:
  ports:
  - port: 8022
    name: goods-web-service-8022
    protocol: TCP
    targetPort: 8022
    nodePort: 8022
  selector:
    app: goods-web-pod
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: goods-web-deployment
  namespace: lnmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goods-web-pod
  template:
    metadata:
      labels:
        app: goods-web-pod
    spec:
      containers:
      - name: go-goods-web
        image: images_goods_web
        imagePullPolicy: Never
        ports:
        - containerPort: 8022